### ISSUE TITLE
Broken update ?

### ISSUE THREAD

**Issue by exigu** [OSM-Plein-Air/OsmAnd-maps-IGN#3]
None of the files released in the latest 1.5 update work in my current version of OsmAnd : 4.7.10

**Comment by Robou** [comment]
Same here but I solved this by chosing "one image file per tile" instead of "sqlitedb file" in the last line of the import new data source screen. And everything worked fine.

**Comment by StC-OSM** [comment]
Thanks for the report and for the workaround! Could you please both give more details on how you import the files? Here it works fine when I download them, retrieve them from Safari's downloads, then select OsmAnd to open them.

**Comment by exigu** [comment]
There you go 

https://github.com/OSM-Plein-Air/OsmAnd-maps-IGN/assets/20596421/da358b3e-3e70-493b-b26a-e1c6f43de94b

As you can see, it doesn't give me any option and imports it straight away, probably with default settings.

**Comment by StC-OSM** [comment]
Android? For some reason (probably another issue report) I was assuming it was on iOS.

**Comment by exigu** [comment]
Android indeed. EMUI 12 on a Huawei device.

**Comment by StC-OSM** [comment]
OK. This might be a red herring, though. Apparently, I left a URL that never was activated by IGN in "IGN Maps", and I must go back to the original URL.  Do you have problems with other maps?

**Comment by exigu** [comment]
> Same here but I solved this by chosing "one image file per tile" instead of "sqlitedb file" in the last line of the import new data source screen. And everything worked fine.

Thanks ! Although it hasn't worked for every file, namely _Traces_ and _Maps_.

**Comment by StC-OSM** [comment]
Still investigating. I had issues with the Android tablet I use for my tests, but I was able to reproduce the issue with IGN BD Ortho tonight (it is not working as is, working after changing the storage option from sqlitedb to one file per tile). I need to understand why changing a URL can trigger this.

I will publish a new version now because I found a bug in two URLs (I had anticipated a change that finally never came), and because Android users have a workaround for the unresolved issue.

**Comment by StC-OSM** [comment]
Interestingly, two maps work directly without the workaround: those which I had to roll back to the previous URLs. This hints at an issue that would be related to the new geopf platform.

**Comment by exigu** [comment]
Ok, this is very strange now.

Context : 
- Files are v1.6
- Default Android import format is sqlite

2 files work out of the box (no need for workaround) :
- Scan OACI
- Maps

1 file works after the workaround
- BD Ortho (although seems blurrier than before) 

The rest doesn't work in any format. 

NOW, the weird thing : I got the _slopes_ layer to work before and it still works if I switch to it BUT it is exactly the same URL as the new one that doesn't work :

https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=GEOGRAPHICALGRIDSYSTEMS.SLOPES.MOUNTAIN&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={0}&TILEROW={2}&TILECOL={1}&FORMAT=image/png

Le mystère s'épaissit...

**Comment by StC-OSM** [comment]
Release v1.7 should work. I had removed the undocumented 's' column from all files except those two whose URL had stayed the same. I still don't know what this 's' column is for, but now I know it must stay.

**Comment by StC-OSM** [comment]
Apparently the 's' column is a flag that says if the tile image at (x, y) is compressed or not

**Comment by exigu** [comment]
> Release v1.7 should work. I had removed the undocumented 's' column from all files except those two whose URL had stayed the same. I still don't know what this 's' column is for, but now I know it must stay.

Much better 👍

And it works right out the box now, no workaround, with default sqlite format.

Unfortunately, these last 2 aren't displaying anything, still :

- Orthophotos 65-80
- Orthophotos 80-95

Also, _Traces_ seems restricted to the Alpine area, dunno if that's normal or not.

**Comment by StC-OSM** [comment]
Orthophotos 65-80 and 80-95 are documented by IGN as work in progress. If you look everywhere in France (northwest regions, Corsica), you'll find some areas that are already covered.

As for Traces I remember reading that it was a collaboration with partners based in Switzerland, so it might make sense.

**Comment by exigu** [comment]
Oh yes, you're right ! Then everything works, well done. 
On a final note, have you thought about joining the _anyGIS online maps collection_  and/or _OsmAnd rendering_ plugin teams ? Seems a decent effort to push online maps internationally.
